### ISSUE TITLE
FindAndUpdate method

### ISSUE THREAD

**Issue by jariwbh** [nassor/mongoose-history#38]
history is not saved when FindOneAndUpdate() method used

**Comment by lsantsan** [comment]
Hi jariwbh, 
Since this project hasn't been updated in a while, I forked it and added the support to updateOne(), findOneAndUpdate(), findOneAndRemove(), and findOneAndDelete().

Here are the links:
**NPM**: [https://www.npmjs.com/package/mongoose-history-updated](https://www.npmjs.com/package/mongoose-history-updated)
**Git**: [https://github.com/lsantsan/mongoose-history-updated](https://github.com/lsantsan/mongoose-history-updated)

The changes include _vkarpov15_ 's [pull request](https://github.com/nassor/mongoose-history/pull/42) and support to Mongoose 5.3.3.

I'll eventually create a new pull request to merge the projects.
