### ISSUE TITLE
support on update, findOneAndUpdate, findOneAndRemove queries

### ISSUE THREAD

**Issue by riteshnus** [nassor/mongoose-history#41]
Its very nice plugin to maintain the update history. Can you tell me do you any plan to implement update, findOneAndUpdate, findOneAndRemove queries to upcoming releases, any ETA? I am eager to know because i need it in my project.

**Comment by lsantsan** [comment]
Hi riteshnus, 
Since this project hasn't been updated in a while, I forked it and added the support to updateOne(), findOneAndUpdate(), findOneAndRemove(), and findOneAndDelete().

Here are the links:
**NPM**: [https://www.npmjs.com/package/mongoose-history-updated](https://www.npmjs.com/package/mongoose-history-updated)
**Git**: [https://github.com/lsantsan/mongoose-history-updated](https://github.com/lsantsan/mongoose-history-updated)

The changes include _vkarpov15_ 's [pull request](https://github.com/nassor/mongoose-history/pull/42) and support to Mongoose 5.3.3.

I'll eventually create a new pull request to merge the projects.

**Comment by ChiKaLiO** [comment]
> mongoose-history-updated

this is what i get when updating:
```
{"_id": {"$oid":"609780548a7d4b4448f3432e"},
"t": {"$date":"2021-05-09T06:25:24.052Z"},
"o":"u",
"d":{
     "updatedAt": {"$date":"2021-05-09T06:25:24.050Z"}
     }
```

even with your version..
